pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'us-east-2'
        TF_IN_AUTOMATION = 'true'
    }

    options {
        timestamps()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Format Check') {
            steps {
                sh '''
                    cd terraform
                    terraform fmt -check -recursive
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                sh '''
                    cd terraform
                    terraform init
                '''
            }
        }

        stage('Terraform Validate') {
            steps {
                sh '''
                    cd terraform
                    terraform validate
                '''
            }
        }

        stage('Checkov Security Scan') {
            steps {
                sh '''
                    checkov -d terraform --soft-fail || true
                '''
            }
        }

        stage('tfsec Security Scan') {
            steps {
                sh '''
                    tfsec terraform --soft-fail || true
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                    cd terraform

                    terraform plan \
                      -var="my_ip_cidr=18.191.242.11/32" \
                      -var="key_name=ec2_ggle_shtskey" \
                      -var="db_password=TempPassword123!"
               '''
            }
        }


    post {
        success {
            echo 'Terraform validation pipeline successful.'
        }

        failure {
            echo 'Pipeline failed. Check logs.'
        }
    }
}